name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Force Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.1.app
    
    - name: Build
      run: xcodebuild clean build -workspace "TriangleTestApp.xcodeproj" -scheme "TriangleTestApp" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      
    - name: Run tests
      run: xcodebuild clean test -workspace "TriangleTestApp.xcodeproj" -scheme "TriangleTestApp" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
